# Change these first
owner: chillgroup # Your GitHub username
repo: relinks-status # Your Github repository name

# Add your sites here
sites:
  - name: Relinks
    url: https://relinks.co/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.relinks.co
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Relinks status
  introTitle: "**Relinks status** is the uptime monitor page."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
