# Change these first
owner: chillgroup # Your GitHub username
repo: relinks-status # Your Github repository name

# Add your sites here
sites:
  - name: Relinks
    url: https://api.relinks.co/healthz

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.relinks.co
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/chillgroup/relinks-status/master/logo-relinks.png
  name: Relinks status
  introTitle: "**Relinks status** is the uptime monitor page."
  introMessage: Monitoring page of Relinks
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
